# Generated by Django 5.2.6 on 2026-09-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('media_type', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=2000)),
                ('hdurl', models.URLField(blank=True, max_length=2000, null=True)),
                ('copyright', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'APOD',
                'verbose_name_plural': 'APODs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupplementalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('found', 'Found'), ('not_found', 'Not found'), ('error', 'Error')], default='not_found', max_length=16)),
                ('matched_title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('extract', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental', to='apod.apod')),
            ],
            options={
                'verbose_name': 'supplemental info',
                'verbose_name_plural': 'supplemental info',
                'ordering': ['source'],
                'constraints': [models.UniqueConstraint(fields=('apod', 'source'), name='unique_supplemental_per_source')],
            },
        ),
    ]
